default: &default
  adapter: postgresql
  encoding: unicode
  username: user
  password: password
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: desafio_dev

test:
  <<: *default
  database: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  primary: &primary_production
    <<: *default
    database: desafio_dev_production
    username: desafio_dev
    password: <%= ENV["DESAFIO_DEV_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: desafio_dev_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: desafio_dev_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: desafio_dev_production_cable
    migrations_paths: db/cable_migrate
