default: &default
  adapter: postgresql
  encoding: unicode
  username: user
  password: password
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: sistema_cnab

test:
  <<: *default
  database: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  primary: &primary_production
    <<: *default
    database: sistema_cnab_production
    username: sistema_cnab
    password: <%= ENV["sistema_cnab_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: sistema_cnab_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sistema_cnab_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sistema_cnab_production_cable
    migrations_paths: db/cable_migrate
